dist:
  name: otel-custom
  description: Basic OTel Collector distribution for Developers
  output_path: ./otel-custom
  otelcol_version: 0.68.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.68.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.68.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.68.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.68.0
  - gomod: go.opentelemetry.io/collector/receiver/prometheusreceiver v0.68.0